# Generated by Django 6.0.7 on 2026-07-27 13:53

import django.db.models.deletion
import time
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=32)),
                ("details", models.TextField()),
                ("previous_hash", models.CharField(max_length=64)),
                ("current_hash", models.CharField(max_length=64)),
                ("timestamp", models.FloatField(default=time.time)),
            ],
        ),
        migrations.CreateModel(
            name="EncryptedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender_key_id", models.CharField(max_length=64)),
                ("receiver_key_id", models.CharField(max_length=64)),
                ("file_path", models.CharField(max_length=512)),
                ("timestamp", models.FloatField(default=time.time)),
                ("size", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="UserIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key_id", models.CharField(max_length=64, unique=True)),
                ("identity_pubkey", models.CharField(max_length=128)),
                ("registered_at", models.FloatField(default=time.time)),
            ],
        ),
        migrations.CreateModel(
            name="PreKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prekey_id", models.CharField(max_length=64)),
                ("prekey_pubkey", models.CharField(max_length=128)),
                ("used", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prekeys",
                        to="kdc.useridentity",
                    ),
                ),
            ],
        ),
    ]
